### ISSUE TITLE
[Device Services] Update examples to be based on Kamakura

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-examples#105]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
Device Service Examples

### Description [**REQUIRED**]
Need to be based on Kamakura

### Describe the solution you'd like
Update go.mod files to use SDK 2.2.0 and 2.2.0 version of go-mods.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by mikahe** [comment]
A couple of findings: deployment/helm/values.yaml has on line 11   type: ClusterIP
even though Readme.md says NodePort is default.
Also edge-ui service template is missing? templates/edgex-ui/edgex-ui-service.yaml

**Comment by lenny-intel** [comment]
> A couple of findings: deployment/helm/values.yaml has on line 11 type: ClusterIP even though Readme.md says NodePort is default. Also edge-ui service template is missing? templates/edgex-ui/edgex-ui-service.yaml

@mikahe , This is unrelated to this issue. Please file a new issue for these items..

**Comment by iain-anderson** [comment]
Example is updated for Levski as of #139 - closing
