### ISSUE TITLE
[Edgex 3.0] Upgrade App Service Examples (minnesota-dev branch) to V3

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-examples#194]
# Must do this on the on the minnesota-dev branch
Update the following custom app service examples .
- [x] simple-cbor-filter
- [x] simple-filter-xml
- [x] simple-filter-xml-http
- [x] simple-filter-xml-mqtt
- [x] advanced-filter-convert-publish
- [x] advanced-target-type
- [x] cloud-event
- [x] cloud-export-mqtt
- [x] custom-trigger
- [x] custom-trigger-nats-rpc
- [x] fledge-export
- [x] influxdb-export
- [x] json-logic
- [x] secrets
- [x] send-command
- [x] Camera Mgmt (waiting for Levski PR https://github.com/edgexfoundry/edgex-examples/pull/197 to merge)

And the following configurable examples:
- [x] app-service-configurable-ibm

Check them off as they are completed.

**Comment by marcpfuller** [comment]
cloud-event is done and merged(#200)

**Comment by marcpfuller** [comment]
PR created for cloud-export-mqtt (#201)

**Comment by marcpfuller** [comment]
PR created for custom_trigger (#202)

**Comment by marcpfuller** [comment]
PR created for custom_trigger nats rpc (#203)

**Comment by marcpfuller** [comment]
PR created for Fledge-export (#204)

**Comment by marcpfuller** [comment]
PR created for influx-export (#205)

**Comment by lenny-intel** [comment]
Done with #214
