### ISSUE TITLE
[Edgex 3.0] Remove random device service and grove-c from example (minnesota-dev branch) and update README

### ISSUE THREAD

**Issue by vli11** [edgexfoundry/edgex-examples#211]
### Affected Services [**REQUIRED**]
device services

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
[Edgex 3.0] Remove random device service and grove-c from example (minnesota-dev branch) and update device-service README to point it to device virtual as an example

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
v3.0

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@lenny-intel @iain-anderson may we remove this device-random in v3?
I made this device service before implementing device-virtual.  There is no real requirement to maintain this one now.

**Comment by lenny-intel** [comment]
@cloudxxx8 , Yes, this is what we discussed doing in TSC today. I have asked @vli11 to do this for Minnesota along with removing the grove-c folder (which isn't a C device service example). A README will be added to point folks to Device Virtual as a Go Device Service example.

This leaves the need for a C Device Service example.

**Comment by lenny-intel** [comment]
closed by #212
