### ISSUE TITLE
Hello, i am creating a app-service to get data from edgex-message bus, but i have trouble when sending data to many topics (i have read in edgex foundry docs but i don't know whether edgex support about publishing messages to many topics). 

### ISSUE THREAD

**Issue by Thinhhoagn0211** [edgexfoundry/edgex-examples#236]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered on Github Discussions (https://github.com/orgs/edgexfoundry/discussions).

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by lenny-intel** [comment]
closing as this was posted to discussions
