### ISSUE TITLE
Examples: Upgrade App Service Examples to V2 SDK

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-examples#38]
Check items have been completed.

Configurable Examples
- [x] app-service-configurable-ibm

Custom Examples
- [x] advanced-filter-convert-publish
- [x] advanced-target-type
- [x] aws-export
- [x] azure-export
- [x] cloud-event
- [x] custom-trigger
- [x] fledge-export
- [x] influxdb-export
- [x] json-logic
- [x] secrets
- [x] send-command
- [x] simple-cbor-filter
- [x] simple-filter-xml
- [x] simple-filter-xml-http
- [x] simple-filter-xml-mqtt

**Comment by AlexCuse** [comment]
Configurable Examples
- [ ] app-service-configurable-ibm

Custom Examples
- [ ] advanced-filter-convert-publish
- [ ] advanced-target-type
- [ ] aws-export
- [ ] azure-export
- [ ] cloud-event
- [ ] custom-trigger
- [ ] fledge-export
- [ ] influxdb-export
- [ ] json-logic
- [ ] secrets
- [ ] send-command
- [ ] simple-cbor-filter
- [ ] simple-filter-xml
- [ ] simple-filter-xml-http
- [ ] simple-filter-xml-mqtt
