### ISSUE TITLE
AWS Deployment template need to be update to Hanoi released images

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-examples#41]
These deployment templates are out of data and need to be update to be using the Hanoi released images, i.e. 1.3.1

This deployment template needs to be updated with the Hanoi images.
https://github.com/edgexfoundry/edgex-examples/blob/master/deployment/templates/aws-fargate.yaml

Use this Hanoi compose file for reference for the image versions.
https://github.com/edgexfoundry/edgex-compose/blob/hanoi/docker-compose-hanoi-no-secty.yml

**Comment by JamesKButcher** [comment]
Need to consider whether to continue with these templates

**Comment by cloudxxx8** [comment]
decided in Core WG meeting on 26-April-2023, closing this issue because we won't use it in v3.0
