### ISSUE TITLE
Want the Hanoi Release "edgex-examples" please.

### ISSUE THREAD

**Issue by Putitii** [edgexfoundry/edgex-examples#70]
Good afternoon,

I'm using EdgeX Foundry in an university project, but can't find the "edgex-examples" folder for the Hanoi release! Currently I'm at the stage that I can't update to a newer version (i.e. Ireland) and I still wanted to look at the information in those folders.

Thank you.

**Comment by cloudxxx8** [comment]
we should have made proper tags.
for the workaround, please try to use the specific commit near to the Hanoi release date.
https://github.com/edgexfoundry/edgex-examples/tree/32e273ed033eb15fe7a94ef2db1287d0b78eac2e

**Comment by lenny-intel** [comment]
Commit `aef67cfaf466e3f0cffec604b79ab10a7c5b2e14 ` was just before the App Service examples got migrated to Ireland

**Comment by Putitii** [comment]
Alright, thank you for the help.
