### ISSUE TITLE
Update kubenetes deployment example to current release

### ISSUE THREAD

**Issue by charithmadhuranga** [edgexfoundry/edgex-examples#74]
Issue- In the deployment kubenetes example hasn’t been updated  

expectation -  updated it to the coming release

**Comment by JamesKButcher** [comment]
@lenny-intel has been updating the example in this repo: https://github.com/lenny-intel/edgex-helm/tree/jakarta 
We need some more testing and a few more eyes on this and then we can make this our default Kubernetes example
