### ISSUE TITLE
Update Raspberry Pi example to Jakarta and RP4

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-examples#76]
Per Kamakura planning meeting (Nov 21).

**Comment by AlexCuse** [comment]
I think I can probably do this - was not aware of an official example but I've been looking to get something set up as well.  Seems like the PR to get device-gpio updated to 2.0 is getting close I imagine that would be a prerequisite?

**Comment by lenny-intel** [comment]
@AlexCuse , the existing example is here: https://github.com/edgexfoundry/edgex-examples/tree/main/deployment/raspberry-pi-4

**Comment by AlexCuse** [comment]
@jpwhitemn @lenny-intel see any reason not to update this to just use the rpi imager and leave scripting an exercise for the user?  good chance I have a low quality SD card but loading with dcat seems like more trouble than its worth, I just plugged it into a monitor to do the initial setup stuff.  I don't see why it wouldn't work but I have not been able to confirm.

**Comment by lenny-intel** [comment]
@AlexCuse , I am not familiar with any of this RPI stuff, so can't help you here.

**Comment by AlexCuse** [comment]
I think I can leave the dcat stuff in place with a general note about how downstream instructions change if you use the imager.  Should have a PR shortly.

**Comment by AlexCuse** [comment]
Sorry for the delay on this - I am done with the first 3 pages just trying to do the programming examples a little differently - checking out the device SDK, copying out the example service and modifying with sed commands etc feels kind of unnatural to me and I think a "whole cloth" example will make it a bit easier for the uninitiated.  

I am close to having my device service example done and assume app service will be very quick.  

You aren't missing that much lenny - go builds on the pi are very slow :)
